#PBS -S /bin/bash

#PBS -V
#PBS -q batch
#PBS -N mpi_openmp
#PBS -l walltime=00:10:00
#PBS -l nodes=venus:ppn=12+marte:ppn=6

source /etc/profile.d/modules.sh

cd $PBS_O_WORKDIR

make sec

in_file="../input/in.txt"
out_file="../output/out.txt"

while read line ; do 
	gen=$(echo $line | tr -s ' ' | cut -f1 -d ' ')
	tam=$(echo $line | tr -s ' ' | cut -f2 -d ' ')
	npr=$(echo $line | tr -s ' ' | cut -f3 -d ' ')
	nth=$(echo $line | tr -s ' ' | cut -f4 -d ' ')

	export OMP_NUM_THREADS= $nth
	
	echo -e >> $out_file
	echo -n "Executing with: " >> $out_file
	echo -e " N_GEN = "$gen" TAM_POB = "$tam "N_PROC = " $npr>> $out_file
	make test_mpi N_GEN=$gen T_POB=$tam N_PROC=$npr
done < $in_file
